-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 10:05:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `nickname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `pseudo_UNIQUE` ON `blog`.`authors` (`nickname` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `blog`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `articleTitle` VARCHAR(45) NOT NULL,
  `articleText` VARCHAR(150) NOT NULL,
  `publicationStart` DATETIME NOT NULL,
  `publicationEnd` DATETIME NOT NULL,
  `importance` INT NOT NULL DEFAULT 0,
  `authors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articles_authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `blog`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_authors1_idx` ON `blog`.`articles` (`authors_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `blog`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commentText` VARCHAR(150) NOT NULL,
  `dateAdd` DATETIME NOT NULL DEFAULT now(),
  `authors_id` INT NOT NULL,
  `articles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comments_authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `blog`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `blog`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comments_authors1_idx` ON `blog`.`comments` (`authors_id` ASC) VISIBLE;

CREATE INDEX `fk_comments_articles1_idx` ON `blog`.`comments` (`articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `blog`.`articles_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`articles_has_categories` (
  `articles_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `categories_id`),
  CONSTRAINT `fk_articles_has_categories_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `blog`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `blog`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_categories_categories1_idx` ON `blog`.`articles_has_categories` (`categories_id` ASC) VISIBLE;

CREATE INDEX `fk_articles_has_categories_articles1_idx` ON `blog`.`articles_has_categories` (`articles_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
